### ISSUE TITLE
Width & Height to accept percentage value

### ISSUE THREAD

**Issue by peps84** [dennisinteractive/video-player-plugin#6]
It would be really useful for the height and width settings to take a percentage value as well as an integer value.

**Comment by peps84** [comment]
So the setting `responsive: 1` is exactly what I was asking for. Could the documentation be updated with this setting please.

**Comment by matt3188** [comment]
Added in latest release v1.0.6 https://github.com/matt3188/video-player-plugin/releases/tag/v1.0.6
